### ISSUE TITLE
What is wrong with enums?

### ISSUE THREAD

**Issue by notdanilo** [Fireboltofdeath/wlausam-bindings#17]
I am trying to use
```rust
part.set_material(&Material::Neon);
```

But it says that it is "Unable to assign property Material. Invalid value 1049436 for enum Material" where 1049436 is a constant value through different executions.

The roblox_enum defines `Neon = 288`.

**Comment by Fireboltofdeath** [comment]
It would appear the generated Rust typings aren't correct, there shouldn't be a borrow there, so the Luau code is receiving a pointer and not the enum.
https://github.com/roblox-rs/bindings/blob/master/build/codegen/rust/conversion.rs

Likewise, we probably want to make all of the Roblox enums `Copy` so that we don't have issues with ownership

**Comment by notdanilo** [comment]
I will try to investigate it
